<h1> a) Import iris dataset from sklearn. <h1>


In [1]:
from sklearn import datasets
import numpy as np

In [2]:
iris = datasets.load_iris()


<h1> b) Split the dataset into training and testing sets using train_test_split()</h1>

In [3]:
X = iris.data
Y = iris.target

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.20,random_state = 0)

<h1> c) Use GaussianNB and print the following: </h1>
i. Confusion matrix <br>
ii. Classification report


In [5]:
from sklearn.naive_bayes import GaussianNB


In [6]:
obj = GaussianNB()


In [7]:
obj.fit(X_train,Y_train)


GaussianNB(priors=None)

In [8]:
Y_pred = obj.predict(X_test)


In [9]:
from sklearn import metrics
print(metrics.confusion_matrix(Y_test, Y_pred))

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


In [10]:
metrics.classification_report(Y_test,Y_pred)


'             precision    recall  f1-score   support\n\n          0       1.00      1.00      1.00        11\n          1       0.93      1.00      0.96        13\n          2       1.00      0.83      0.91         6\n\navg / total       0.97      0.97      0.97        30\n'

<h1> d) Use MultinomialNB and print the following: </h1>
i. Confusion matrix<br>
ii. Classification report

In [11]:
from sklearn.naive_bayes import MultinomialNB
ob = MultinomialNB()
ob.fit(X_train,Y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [12]:
Y_pred = ob.predict(X_test)


In [13]:
from sklearn import metrics
print(metrics.confusion_matrix(Y_test, Y_pred))

[[11  0  0]
 [ 0  0 13]
 [ 0  0  6]]


In [14]:
metrics.classification_report(Y_test,Y_pred)


C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


'             precision    recall  f1-score   support\n\n          0       1.00      1.00      1.00        11\n          1       0.00      0.00      0.00        13\n          2       0.32      1.00      0.48         6\n\navg / total       0.43      0.57      0.46        30\n'